### ISSUE TITLE
Another LED driver

### ISSUE THREAD

**Issue by michal-reiter** [dave-code-ruiz/elkbledom#13]
Hello,

I have a LED driver which uses the same Android app (duoCo Strip), but is not recognized by HA.
It is a brand new installation of HA - it seems that gatttool is no longer available.

After giving the command at the terminal:  "bluetoothctl info MAC_address"
I get following result:
Device BE:FF:50:00:92:A4 (public)
    Name: ELK-BLEDOM
    Alias: ELK-BLEDOM
    ... 
    UUID: Human Interface Device   (00001812-0000-1000-8000-00805f9b34fb)

Please guide me thru on how to use bluetoothctl if anything more is needed to add that strip to the list.

**Comment by dave-code-ruiz** [comment]
For info you provide i think is same strip, and not change are needed.
You can try some options,
   1 - bluetoothctl stay connected to strip, you need to disconnect, use "bluetoothctl disconnect" and try add integration again.
   2 - other software can stay connected to strip, try to disconnect it.
   3 - sometimes distance to strip can generate errors, reduce distance to minimal and try again.
You can use bluetoothctl to post here more information, do this:
   1 - exec "bluetoothctl connect BE:FF:50:00:92:A4"
   2 - exec "bluetoothctl" then "menu gatt" then "list-attributes"
   3 - report me results

**Comment by michal-reiter** [comment]
Hello,

Re 1. I did "bluetoothctl disconnect", and also "bluetoothctl remove". I did it a few times between the attempts.

Re 2. I have unpaired the strip from the application on my mobile. To be sure I have switched off Bluetooth on my mobile.
The strip was never paired with any other device - so I'm sure now it is not attempting any communication (except Pi obviously).
I tried to switch off all surrounding Bluetooth devices. I haven't localized one device, which seems to be some TV from the neighborhood (40:5B:___) - RSSI over 80.

Re3. To be sure I have moved Pi just next to the strip - approx. 20 cm. Bluetoothctl reporting RSSI from the strip in a range from -22 to -28. I guess it is much more than needed.

I issue bluetoothctl, then "connect BE:___"
![image](https://user-images.githubusercontent.com/120309810/209813296-fe17fff8-272e-4105-9cbe-a330f7ac6c12.png)

I tried pairing - no success
![image](https://user-images.githubusercontent.com/120309810/209813648-33e50348-fa38-4953-af44-039a2461e62a.png)

**Comment by michal-reiter** [comment]
Hello again,

I read a little bit about that "le-connection-abort-by-local" issue - it seems to be "bluez" problem.
I decided to give it another try with another setup.
For test purposes: I abandoned HomeAssistant OS 9.4 issued on 1st of December 2022.
I have downloaded the lite Raspberry Pi OS dated 22nd of September 2022.

Bluetoothctl seems to work kind of differently.
Now I have managed to connect:
![image](https://user-images.githubusercontent.com/120309810/209822139-d583232a-0e50-45b9-9b8c-b5b206761712.png)
 then "menu gatt" -> "list-attributes" gave me the following outcome: 
![image](https://user-images.githubusercontent.com/120309810/209822703-75520c1b-e0c8-44f2-b9ab-d48a66f30097.png)

So based on that entry indicated with hand made red arrow - I assume that the strip I have is supported. Right?
Kindly please -  confirm that.

Thank you for your time
BR
M

**Comment by dave-code-ruiz** [comment]
Yes, i think you have the same led strip

**Comment by dave-code-ruiz** [comment]
Try in HomeAssistant and add elkbledom integration, you can use debug log to see more information of posible connection errors. In configuration.yaml:

```
logger:
  default: info
    custom_components.elkbledom: debug
```

**Comment by michal-reiter** [comment]
I returned to HomeAssistant OS and added "logger" entry as indicated above into configuration.yaml
In the beginning, bluetoothctl was behaving in the same way.
But after some tweaks, it started to work in a way as I observed on Rapsberry OS.
I managed to connect to the strip - it displayed attributes, etc.
So now I'm able to CONNECT TO THE STRIP using bluetoothctl.
One of the things I did - in the "integrations window" I turned on Bluetooth debugging on. And also I have changed setting called "passive scanning" - a few times on/off between attempts. To be honest I have no idea what caused bluetoothctl is able to connect.
home-assistant.log contains some homeassistant.components.bluetooth enries - but nothing that would cause me curious.

But when I try to add "LED BLE" integration - it immediately ends up with a pop-up window saying that "no unconfigured devices found", with the only possibility to close the popup window.
No trace in home-assistant.log for LED BLE / elkbledom.
Maybe only 
2022-12-28 19:45:02.815 INFO (SyncWorker_1) [homeassistant.loader] Loaded led_ble from homeassistant.components.led_ble
which appears at system restart.

**Comment by dave-code-ruiz** [comment]
Ok, ledble is other integration,  my integration is elkbledom, and you need before install HACS and download elkbledom repository,  follón install instructions in realmente.md

**Comment by dave-code-ruiz** [comment]
https://www.wundertech.net/how-to-install-hacs-on-home-assistant/

**Comment by michal-reiter** [comment]
Hello,

My strip does not work with "LED_BLE" integration, but it works with "elkbledom".
Thank you for your time.

BR
Michał

**Comment by dave-code-ruiz** [comment]
I'm very glad,

enjoy using the integration

Bye

**Comment by michal-reiter** [comment]
I would have some feedback to "readme.md" and possibly to interface.
Possibly I could involve in some improvements and translation into Polish - if you would have the patience to answer my questions.
What you say?

BR
M

**Comment by dave-code-ruiz** [comment]
I say YES, thanks for your time.
If you know how to, you can create a PR (Pull Requests) with file "/translations/pl.json" if not know how to, send me texts in new issue.
You can use copy of file "/translations/en.json" and change english texts for polish texts.
Regards
