### ISSUE TITLE
BLEDOM device no longer being detected

### ISSUE THREAD

**Issue by Korpip** [dave-code-ruiz/elkbledom#14]
I have a cheap BLEDOM device that was working.
I though it may be someone the recent updates but I downgraded to version 0.0.4 which I was sure was working but the device was not detected by the plugin.   
Was there a recent change in HA that limited this addon?

The specific device seems to be detailed on this Github page https://github.com/arduino12/ble_rgb_led_strip_controller

**Comment by dave-code-ruiz** [comment]
I think you need install new "bluetooth" integration :

https://www.home-assistant.io/integrations/bluetooth/

Yes HA have important changes in bluetooth devices

Luck!

**Comment by Korpip** [comment]
After some new updates to HA I am able to complete the connection and use the device.   
I now have a problem where every reboot I have to reconnect the Bluetooth device.

It was working just fine before.  Thank you for confirming that this is a HA issue.  I will have to find a way to report the bug to HA.
