### ISSUE TITLE
ModuleNotFoundError: No module named 'custom_components.xiaomi_gateway3'

### ISSUE THREAD

**Issue by gchrisak** [dave-code-ruiz/elkbledom#2]
Hello, im getting the bellow error in the new version.  The integration wont load.

File "/config/custom_components/elkbledom/__init__.py", line 8, in <module>
    from .elkbledom import BLEDOMInstance
  File "/config/custom_components/elkbledom/elkbledom.py", line 8, in <module>
    from custom_components.xiaomi_gateway3.core.device import update
ModuleNotFoundError: No module named 'custom_components.xiaomi_gateway3'

**Comment by dave-code-ruiz** [comment]
use new version 0.0.3
