### ISSUE TITLE
Issue on Config / Setup - Missing Parameter

### ISSUE THREAD

**Issue by smeg9** [dave-code-ruiz/elkbledom#23]
Hi,

Great integration, I encountered an issue when adding the integration for my device.  I was getting "Unknown Error" 

Log file pointed to a missing parameter on line 171 of config_flow.py.

Looking through history it appears that there is now a 'delay' parameter required for BLEDOMInstance - I noticed this has been updated elsewhere in the codebase but looks like config_flow.py was missing still.

I verified by passing a hard-coded parameter by directly editing the file and was then able to continue to with the setup and now the integration works well.

**Comment by JustJoshTikTok** [comment]
Ive had the same issue

**Comment by JustJoshTikTok** [comment]
can you share your config_flow.py modified file?

**Comment by dave-code-ruiz** [comment]
Issue solved in version 1.0.6.

Sorry, my mistake.
