### ISSUE TITLE
UID Not shown

### ISSUE THREAD

**Issue by marvinto23** [dave-code-ruiz/elkbledom#24]
Hi i do have some uid which are not listed,

7579F3BF-064A-6559-852E-2CDB7D8A74D8

A3А680D5-9E15-CAA7-42E3-E71777F36314

also i attached a screenshot
![E6445F74-D841-449C-AC09-55735CBB1DE2](https://github.com/dave-code-ruiz/elkbledom/assets/84294162/248f82af-9973-441c-aa50-a7c24b445bc4)

**Comment by dave-code-ruiz** [comment]
Hi this uid is not the same as Characteristics uuid, 

You can use gatttool -I to get your correct Characteristics uuid, when you get Characteristics uuids each led strip has a different Characteristics numbers.

elkbledom led strip show:

handle: 0x0002, char properties: 0x12, char value handle: 0x0003, uuid: 00002a00-0000-1000-8000-00805f9b34fb
handle: 0x0005, char properties: 0x10, char value handle: 0x0006, uuid: 0000fff4-0000-1000-8000-00805f9b34fb
handle: 0x0008, char properties: 0x06, char value handle: 0x0009, uuid: 0000fff3-0000-1000-8000-00805f9b34fb

Thanks
