### ISSUE TITLE
set_effect_speed function

### ISSUE THREAD

**Issue by antibill51** [dave-code-ruiz/elkbledom#25]
Hi. 
First thank you for this great work!

I can't find how to change the speed of the effects. I can see the set_effect_speed function but I can't find anything on the HA side.

Thanks !

**Comment by dave-code-ruiz** [comment]
HA haven't this opcion in light components and i can't developed it for HA

**Comment by dave-code-ruiz** [comment]
I keep the issue open in case someone knows how to do it

**Comment by ynsgnr** [comment]
Here is how to do it: https://github.com/dave-code-ruiz/elkbledom/pull/40

**Comment by antibill51** [comment]
@ynsgnr Thanks! I will try it tonight.

**Comment by dave-code-ruiz** [comment]
tested and solved
