### ISSUE TITLE
Effect reset when changing brightness

### ISSUE THREAD

**Issue by dave-dube** [dave-code-ruiz/elkbledom#26]
If i set en effect (eg: blink_green), the led are starting linking green.  nice.  But if i change brightness the effect is stopped and led are back in "full green".
So impossible to change brightness when using effects
Using this Led strip:
- 20MAC864WB BLK

**Comment by dave-code-ruiz** [comment]
Yes,  impossible to change brightness when using effects, I'll check it when I have some time

**Comment by dave-dube** [comment]
Hello.

Yes i can do few test.
using the Remote, yes i can change the brightness during using effects, and the effects is not stopped.  So for sure using the remote it works.

now, to test using apps..... i will need probably your help to know which (and how) test i should do.

Thanks

**Comment by ynsgnr** [comment]
This should fix it: https://github.com/dave-code-ruiz/elkbledom/pull/41

**Comment by dave-dube** [comment]
Thanks @ynsgnr.  I installed manually your 2 new files on my environment and did few tests.  Everything works fine and now the effect is not reset anymore when changing brightness.
Thanks so much
