### ISSUE TITLE
Pool Lights from amazon

### ISSUE THREAD

**Issue by tablatronix** [dave-code-ruiz/elkbledom#27]
There are a bunch of these on amazon, surprisingly they hit amazon before aliexpress, they are relatively new.

Here is some info from the one I bought, do you think these are fairly the same? I can try to test/debug when I get a chance

![Screenshot 2023-06-06 at 9 07 35 PM](https://github.com/dave-code-ruiz/elkbledom/assets/807787/cca6af3b-f56a-4ffb-9874-da0baeaa83b7)

![IMG_8976](https://github.com/dave-code-ruiz/elkbledom/assets/807787/9d8407d3-41b3-4ac4-ab2e-8534e9f2097b)
![IMG_8977](https://github.com/dave-code-ruiz/elkbledom/assets/807787/40347768-102c-474b-a9da-e64675ee8e84)
![IMG_8978](https://github.com/dave-code-ruiz/elkbledom/assets/807787/44a6613b-f199-4dd6-9e74-5e608747cb98)

**Comment by dave-code-ruiz** [comment]
Yes i think it is the same strip
