### ISSUE TITLE
wrong behavior detected by @diandr6 94% brightness 

### ISSUE THREAD

**Issue by dave-code-ruiz** [dave-code-ruiz/elkbledom#28]
In #22 the user @diandr6 detected wrong behavior, she explain it : 

> The lamp works and connects, but the white color does not behave as usual. For the interface, the lamp is always at 94% brightness (even if the HA interface is set to 1%) and the selected color mode. Warm white and cool white modes do not work correctly. Warm white = 10,000K and cool white = 1,000,000K when the actual range is 3000K to 6500K. When the lamp is turned on in white mode, the interface is displayed as in color mode (blue or light yellow) and turning off / on the lamp switches it to color mode.

And with video

> I think the video will make it clearer what's going on.
> https://youtu.be/AtCGdVATMDE

**Comment by raulgbcr** [comment]
You can actually set the color temp range in kelvins using the light class and configure a range for each light, it will display the correct range in HA and limit you to those, have done something similar in https://github.com/raulgbcr/lednetwf_ble/blob/main/light.py which is heavily based on your integration code!

**Comment by dave-code-ruiz** [comment]
Thnks @raulgbcr i implement it when have time.

I redirect my support features to your repo when the strip is supported for your code.

**Comment by ynsgnr** [comment]
This should fix it: https://github.com/dave-code-ruiz/elkbledom/pull/41
