### ISSUE TITLE
Changing brightness slowly ruins the color

### ISSUE THREAD

**Issue by Double-A-92** [dave-code-ruiz/elkbledom#30]
When I change the brightness with the "Light" panel on my home view, the set color slowly degrades towards pure Red, pure Blue or pure Green.

E.g.

- Set a white-ish color at 100%
- Change it to 1%
- Change it back to 100% 
- Color becomes a bit more orange
- Change it to 1% and back to 100%
- Color becomes more red
- Repeat a few times
- Color is pure Red

![image](https://github.com/dave-code-ruiz/elkbledom/assets/2192982/0bbeb6f8-864e-4c17-940e-b5c60cb66371)

In real life this color has become Red at 30%

Maybe some rounding or integer division error while calculating the new RGB value?

**Comment by ynsgnr** [comment]
This should fix it: https://github.com/dave-code-ruiz/elkbledom/pull/41
