### ISSUE TITLE
Color temperature widget has too high values

### ISSUE THREAD

**Issue by Double-A-92** [dave-code-ruiz/elkbledom#31]
In this view to set the color temperature the values range from 10000K to 999999K, which is too much.

A reasonable range would maybe be 1000K to 9999K.  I assume there is maybe some wrong decimal offset..?

![image](https://github.com/dave-code-ruiz/elkbledom/assets/2192982/74dfe5fc-a6a0-4af7-bcee-4536bd5a8a85)

Also the color for me does not work properly. It's either green-ish at around 10000K, and everywhere else it's a white-blue. 
I don't know if it's just my LED strip not supporting it, or if it's because of the high values,

**Comment by Jammarman** [comment]
I am also experiencing this

**Comment by GormYa** [comment]
I think we should make this range manageable from the settings page. As a result, each user may define their own range that is supported by their LED strip.

**Comment by Double-A-92** [comment]
I think the problem is caused by following lines in light.py

```
@property
    def max_mireds(self):
        return 100

@property
    def min_mireds(self):
        return 1
```

They overwrite the good defaults (2000 - 6500K) with very high values for some reason.

**Comment by dave-code-ruiz** [comment]
Thanks, you may be right
I review it soon

**Comment by Double-A-92** [comment]
Btw I just saw that the function `async def set_color_temp(self, value: int):` in `elkbledom.py` also depends on those values  (1 - 100).
