### ISSUE TITLE
Error adding entities for domain light with platform elkbledom (Since HA 2023.8.0)

### ISSUE THREAD

**Issue by tracedebrake** [dave-code-ruiz/elkbledom#32]
Logger: homeassistant.components.light
Source: helpers/entity_platform.py:619
Integration: Lumière ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 20:13:24 (2 occurrences)
Last logged: 20:13:24

Error adding entities for domain light with platform elkbledom
Error while setting up elkbledom platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: homeassistant.helpers.device_registry.DeviceRegistry.async_get_or_create() got multiple values for keyword argument 'config_entry_id'

**Comment by tracedebrake** [comment]
The culprit might be here: https://github.com/home-assistant/core/pull/95547

**Comment by dave-code-ruiz** [comment]
I publish 1.0.8 with your fix, try it please and post results

**Comment by tracedebrake** [comment]
I confirm that the fix works with the latest 2023.8.1 :)

**Comment by dave-code-ruiz** [comment]
@tracedebrake thnks
