### ISSUE TITLE
FutureWarning: BLEDevice.rssi is deprecated and will be removed in a future version of Bleak, use AdvertisementData.rssi instead return self._device.rssi

### ISSUE THREAD

**Issue by tracedebrake** [dave-code-ruiz/elkbledom#33]
Logger: py.warnings
Source: custom_components/elkbledom/elkbledom.py:186
Integration: Elkbledom ([documentation](https://github.com/dave-code-ruiz/elkbledom), [issues](https://github.com/dave-code-ruiz/elkbledom/issues))
First occurred: 20:13:21 (3 occurrences)
Last logged: 20:14:49

/config/custom_components/elkbledom/elkbledom.py:186: FutureWarning: BLEDevice.rssi is deprecated and will be removed in a future version of Bleak, use AdvertisementData.rssi instead return self._device.rssi

**Comment by dave-code-ruiz** [comment]
I know and try develop it but change a lot.

Finally i disable use of rssi in next version 

Expect to it

**Comment by dave-code-ruiz** [comment]
new release 1.1.0 solved this issue, please test it.

i close the issue
