### ISSUE TITLE
Light strip is not detected as a device

### ISSUE THREAD

**Issue by dwaned** [dave-code-ruiz/elkbledom#34]
Home Assistant 2023.8.0
Supervisor 2023.07.1
Operating System 10.4
Frontend 20230802.0 - latest

Added integration via HACS with latest version, and when adding device, it finds the lights, blink test is successful, but the lights show as entity, unable to control.

<img width="1060" alt="image" src="https://github.com/dave-code-ruiz/elkbledom/assets/17186019/6fb18287-f91f-4de1-bcd2-7f5d34572730">

**Comment by dave-code-ruiz** [comment]
Ok probably you have and error in your log

Please post error here.

If you dont know how to, please search how to in other issue i explain it

**Comment by doudigit** [comment]
@dave-code-ruiz i got the same problem. Here is the log

`Logger: homeassistant.components.light
Source: helpers/entity_platform.py:619
Integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 05:36:20 (6 occurrences)
Last logged: 05:55:55

Error adding entities for domain light with platform elkbledom
Error while setting up elkbledom platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: homeassistant.helpers.device_registry.DeviceRegistry.async_get_or_create() got multiple values for keyword argument 'config_entry_id'`

**Comment by tracedebrake** [comment]
Same as #32

**Comment by LexMrack** [comment]
After updating HA to 2023.8.0, I had the same thing. After the rollback to 2023.7, everything came back.
После обновления HA на 2023.8.0 у меня было тоже самое. После отката на 2023,7 вернулось всё обратно.

**Comment by tracedebrake** [comment]
![image](https://github.com/dave-code-ruiz/elkbledom/assets/43702274/ad664d2d-af09-4d96-9e68-59ccef4c504a)

There was a change in 2023.8; he must adapt his code to https://github.com/home-assistant/core/pull/95547

It'll be broken as long as he or someone else fix it. Might give it a shot.

**Comment by dave-code-ruiz** [comment]
Sorry i am on vacation in August 

Bad month for broke core code

May be fix it in long time, Sorry for the inconvenience.

**Comment by dave-code-ruiz** [comment]
A can accept an other user PR if someone do it

**Comment by tracedebrake** [comment]
Change proposed in light.py

That function is meant to return a DeviceInfo as defined here https://github.com/home-assistant/core/blob/614f3c6a15713aa762269f7c628d4420987cbd4c/homeassistant/helpers/entity.py#L177
So it was probably working by accident before

**Comment by tracedebrake** [comment]
OK everybody, issue is fixed. Debugged it on a sunday morning on the toilet so you all owe me a beer.

Might take a look at #33 soon.

Have a great summer everybody.

**Comment by dwaned** [comment]
Thank you! Fix is confirmed 🍻 🍺

**Comment by dave-code-ruiz** [comment]
@tracedebrake thnks for your help in my vatacions

**Comment by dave-code-ruiz** [comment]
Thnks @dwaned too for your support
