### ISSUE TITLE
Does not connect to the device

### ISSUE THREAD

**Issue by LexMrack** [dave-code-ruiz/elkbledom#37]
It finds it instantly, but when trying to connect, it constantly turns and cannot connect in any way. As a result, it issues a message to reconnect.
In HA 2023.07, the tape was installed at least every other time. Then I was constantly buggy and passed out, But sometimes it worked. After updating this integration, nothing has changed.
If you update HA from ,07 to ,08, then the device remained, but there was not a single object, and if you install it immediately on ,08, it does not connect.

Находит мгновенно, но при попытке соединиться постоянно крутит и никак не может соединиться. В итоге выдает сообщение на повторное соединение. 
В HA 2023.07 лента хоть через раз, но устанавливалась. Потом глючила постоянно и отрубалась, Но иногда работала. После обновления этой интеграции ничего не изменилось.
Если обновить HA с ,07 на ,08 то устройство оставалось, но ни одного объекта не было, а если установить сразу на ,08 то не подключается.

![2023-08-07_22-46-39](https://github.com/dave-code-ruiz/elkbledom/assets/139388477/df4bbaac-8084-4158-af50-b46e65a00a79)
![2023-08-07_22-57-08](https://github.com/dave-code-ruiz/elkbledom/assets/139388477/391240d3-aa7e-4929-9adb-4d20cbcede50)

**Comment by tracedebrake** [comment]
Hello, did you read the Supported strips section in readme.md? 

Please confirm your led strip uuid.

**Comment by LexMrack** [comment]
I read and set up according to the instructions.
On a tablet, the feed works through the application without problems (the application logo is the same as yours).
After HA, I could not configure anything for 2 days after updating to 2023.08.
Right now, as I write, the feed is connected, working, changing color and effects, but that was before the update.
After 1-4 hours, it will be impossible to connect to the feed as before. We will have to remove the tape from HA, overload HA 10 times and, perhaps, it will pull up again.

Я читал и настраивал по инструкции.
На планшете лента работает через приложение без проблем (логотип приложения такой же как и у вас).
Через HA я 2 дня ничего не мог настроить после обновления на 2023,08.
Прямо сейчас, когда я пишу, лента подключилась, работает, меняет цвет и эффекты, Но это было и до обновления.
Через 1-4 часа подключиться в ленте будет невозможно как и раньше. Прийдется удалять ленту из HA, 10 раз перегрузить HA и, возможно, она опять подтянется.

![Screenshot_20230808_133015_BLE Scanner](https://github.com/dave-code-ruiz/elkbledom/assets/139388477/53fcfe2e-cdca-483c-9176-5eb1b579ce00)

**Comment by tracedebrake** [comment]
1. Use the latest Home Assistant (2023.08.1)
2. Delete your strip from extension menu
3. Disconnect your strip from the wall and do not reconnect it yet.
4. Reboot HA
5. Once HA has rebooted and fully reloaded, reconnect the strip.
6. Add the strip with the integration

If it works right away and stop working hours later, I would replace my USB Bluetooth adapter by known high end, long range model such as the Feasycom FSC-BP119[https://fr.aliexpress.com/item/4000087707727.html?spm=a2g0o.order_list.order_list_main.17.c2fb5e5bsYjAsH&gatewayAdapt=glo2fra](url). Also, moving your Bluetooth adapter away from Wi-Fi and other 2.4GHz souce might help.

**Comment by LexMrack** [comment]
I installed the ESP Bluetooth Proxy on the tent and threw out the Bluetooth stick.
Thanks!

Установил ESP Bluetooth Proxy на платку и выкинул стой Bluetooth стик. 
Спасибо!
