### ISSUE TITLE
Automation and Home Assistant

### ISSUE THREAD

**Issue by LexMrack** [dave-code-ruiz/elkbledom#38]
I ran into a HA problem when creating automation.
It is only possible to turn on/off/switch the state.
Is it possible to change the color and launch the effect through automation?

**Comment by tracedebrake** [comment]
When you create your automatisation in HA, in action do not select your device.

Use ''call a service'' and use light.turn_on ; then select your device and you'll see ton of options, including color, brightness etc...

**Comment by LexMrack** [comment]
Thanks! with this answer, you solved 6 problems for me!

Спасибо! этим ответом вы мне решили 6 проблем!
