### ISSUE TITLE
Error log timeout

### ISSUE THREAD

**Issue by Next9999** [dave-code-ruiz/elkbledom#4]
Hi
happy to see that "ELKBLEDOM" is now integrated with HA

i have two ELKBLEDOM...

- one is white.... this one is working
- RGB.. this one is not working

===================

This error originated from a custom integration.

Logger: custom_components.elkbledom.elkbledom
Source: custom_components/elkbledom/elkbledom.py:196
Integration: Elkbledom (documentation, issues)
First occurred: 16:42:38 (1 occurrences)
Last logged: 16:42:38

Error getting status: Device with address BE:FF:20:00:D8:C8 could not be found. Try increasing `timeout` value or moving the device closer.

**Comment by dave-code-ruiz** [comment]
I think it is a distance error, try gatttool and try use it in 1 meter between HA and ELKBLEDOM

**Comment by Next9999** [comment]
it is working now :-)
