### ISSUE TITLE
Light strip fails to add

### ISSUE THREAD

**Issue by DaTrafficCone** [dave-code-ruiz/elkbledom#45]
Hi. I decided to try this project as I have an ELKBLEDOM Strip in my kitchen. I set up Bluetooth on my server (generic-x86) and installed the integration. The integration finds my light strip but when I try to go add it i get an endless spinning circle. ![image](https://github.com/dave-code-ruiz/elkbledom/assets/103389792/c1a1b737-c2fc-43ca-b7ac-a092a8be8598)

If i leave the app, I get an unknown error. Nothings shows up in the logs, just a warning saying that this is a custom integration. I'm pretty new to bluetooth Hass devices as i just got the Bluetooth integration working on my server.

**Comment by dave-code-ruiz** [comment]
Use debug log to see more information of posible errors.

In configuration.yaml:

```
logger:
  default: info
  logs:
    custom_components.elkbledom: debug
```

Post log results.

but i think it is distance error, move strip beside raspberry for discart this possible issue

**Comment by DaTrafficCone** [comment]
Alright, now I get these 2 errors. I tried moving my server right next to the strip but still nothing.


Error getting status: ELK-BLEDOM - 00:00:00:00:00:00: Failed to connect after 4 attempt(s): TimeoutError
Error getting status: ELK-BLEDOM - 00:00:00:00:00:00: Failed to connect after 4 attempt(s): failed to discover services, device disconnected

**Comment by dave-code-ruiz** [comment]
Hi, The integration does not manage the connections , this error is throws from the bleak library (https://pypi.org/project/bleak/) it is possible to be distance error (now discarted) , or strip is connected to other device, or the strip staying blocked (try turn off, turn on), or something similar, but integration is not the problem

**Comment by dave-code-ruiz** [comment]
@dilpish say :
I had a similar problem with an LED strip when I used weak USB power. I connected it to a more powerful power supply and everything worked out.

Dont use battery and try to use power supply with more amps, post your results

**Comment by t0mc1k** [comment]
Power supply sufficient, distance right next to the bluetooth receiver. It doesn't work. I enter the name of the device and click send, then it asks "Did the light blink" and nothing. nothing flashes. adding fails.

**Comment by dave-code-ruiz** [comment]
Please post your debug log, can you see how to in read.me

**Comment by dave-code-ruiz** [comment]
ok, i think it was possible the same issue but no.
Like i said you in another post:
The integration does not manage the connections , this error is throws from the bleak library (https://pypi.org/project/bleak/) it is possible to be distance error (now discarted) , or strip is connected to other device, or the strip staying blocked (try turn off, turn on), or something similar, but integration is not the problem

**Comment by t0mc1k** [comment]
I tried turning it on and off. I also tried powering down, waiting a while and reconnecting. still the same. the distance from bluetooth is about 15cm. the other device is not connecting i have not paired it with any application i have deleted all of them both from ios and android. even after erasing i tried the same procedure to turn off/on, disconnect from the network, etc. the device is found. it connects but when it says to blink it doesn't blink. Video https://www.youtube.com/watch?v=YT1Ll8yoJOY :)

**Comment by dave-code-ruiz** [comment]
Woowww, now i understand what occurs. !!!!
Ok when answer for you did it blink, you need to click the CHECK on the left for confirm blink.
If you dont check it , process is canceled .
Try clicking the check

**Comment by t0mc1k** [comment]
I've tried that too, otherwise I wouldn't be writing here. The device is added, but it doesn't work. The control does not work. I'm not stupid to post here without trying all the methods.

**Comment by dave-code-ruiz** [comment]
Ok, add the device, active debug mode, click some controla, turn on , turn off, change color, etc
And then obtain debug log and post it here

**Comment by t0mc1k** [comment]
interesting that the brightness control works but the others don't. nor off and on, or changing colors or effects.  Power supply is 2a, 5V charger. Led strip is placed next to the server. And in the log I noticed that the signal fluctuates from 71rssi to 121rssi. I don't understand why it does this. I'm guessing it's a bug? Should i get rid of it and buy a better bluetooth controller? But interesting that through the mobile phone app the baud works for me in the next room too.  other devices I have via bluetooth humidity and temperature sensors are very far away from the server and they work great.

debug log:
https://file.io/nd7yM7jLI2Hp

**Comment by dave-code-ruiz** [comment]
Ok, i saw all you send, and power supply , bluetooth and rest was correct. no bug. no need better bluetooth, and you can put your strip far away. 

I saw too the log file and no ERROR in it, strip connect and no fails to add no have same issue than @DaTrafficCone 

Finally your strip model is MELK , i have an issue open about your problem, #11 and you need to send to strip two init commands , i dont know why , something weird, but work fine:

`
sudo gatttool -b BE:16:F8:1D:D6:66 --char-write-req -a 0x0009 -n 7e0783 
sudo gatttool -b BE:16:F8:1D:D6:66 --char-write-req -a 0x0009 -n 7e0404 
`
after that you can work with your strip normally

Try and post results

**Comment by t0mc1k** [comment]
Hey, boss. I'm sorry I'm only writing now, I've had a lot of work to do. I tried your tip. but without success. I can't write this data according to the gatttol. I tried restarting, turning off/on strip and etc. it won't let me write.

root@T0mc0-HA:~# sudo gatttool -b BE:16:F8:1D:D6:66 --char-write-req -a 0x0009 -n 7e0404
Characteristic Write Request failed: Attribute can't be written
root@T0mc0-HA:~# sudo gatttool -b BE:16:F8:1D:D6:66 --char-write-req -a 0x0009 -n 7e0783
Characteristic Write Request failed: Attribute can't be written
root@T0mc0-HA:~# sudo gatttool -b BE:16:F8:1D:D6:66 --char-write-req -a 0x0009 -n 7e0783
Characteristic Write Request failed: Attribute can't be written
root@T0mc0-HA:~# sudo gatttool -b BE:16:F8:1D:D6:66 --char-write-req -a 0x0009 -n 7e0404
Characteristic Write Request failed: Attribute can't be written
root@T0mc0-HA:~# sudo gatttool -b BE:16:F8:1D:D6:66 --char-write-req -a 0x0009 -n 7e0404
Characteristic Write Request failed: Attribute can't be written
root@T0mc0-HA:~# sudo gatttool -b BE:16:F8:1D:D6:66 --char-write-req -a 0x0009 -n 7e0783
Characteristic Write Request failed: Attribute can't be written
root@T0mc0-HA:~# sudo gatttool -b BE:16:F8:1D:D6:66 --char-write-req -a 0x0009 -n 7e0404
connect to BE:16:F8:1D:D6:66: Software caused connection abort (103)
root@T0mc0-HA:~# sudo gatttool -b BE:16:F8:1D:D6:66 --char-write-req -a 0x0009 -n 7e0783
Characteristic Write Request failed: Attribute can't be written

**Comment by dave-code-ruiz** [comment]
There are only one connection to led strip, if HA is connected to strip, gatttool not work.

1- You need to delete HA integration with elkbledom strip.
2- restart strip
3- send commands with gatttool, first 7e0783 and second 7e0404 in this order.

Finally connect HA integration again

good luck
