### ISSUE TITLE
Any way to also control with App (I have Magic Lantern)?

### ISSUE THREAD

**Issue by loopy321** [dave-code-ruiz/elkbledom#54]
I see you mentioned below that there can only be one connection at a time.  Is it possible to allow the app to connect while HA integration is loaded?
Right now the effect is wrong and there is now way for me to change it to the desired value.
This is on a MELK with character 0000FFF3-0000-1000-8000-00805F9B34FB

==========================

There are only one connection to led strip, if HA is connected to strip, gatttool not work.

1- You need to delete HA integration with elkbledom strip.
2- restart strip
3- send commands with gatttool, first 7e0783 and second 7e0404 in this order.

Finally connect HA integration again

good luck

_Originally posted by @dave-code-ruiz in https://github.com/dave-code-ruiz/elkbledom/issues/45#issuecomment-1790484240_

**Comment by dave-code-ruiz** [comment]
Yes , HA Integration have a configuration with time connected in seconds (Disconnect delay or timeout) if not is zero you connect to strip send command and disconnect to left free connection
