### ISSUE TITLE
HA OS

### ISSUE THREAD

**Issue by n4tur3502** [dave-code-ruiz/elkbledom#56]
How can I use this in HAOS? I cant run the commands you list to get the uuid and stuff.

**Comment by dave-code-ruiz** [comment]
Follow the installation instructions and install the bluetooth component. If you have a compatible strip, when you reset it, it will automatically discover your strip and you can add it.

Uuid is only needed for uncompatible strips and for discover possible errors

**Comment by n4tur3502** [comment]
Ok, when i restarted the led strip it actually shows in discovered. But for some reason does not actually connect to it.

**Comment by dave-code-ruiz** [comment]
You need enable debug mode:

https://github.com/dave-code-ruiz/elkbledom#enable-debug-mode

I dont know if you can do it in HAOS

**Comment by dave-code-ruiz** [comment]
Show me debug log of elkbledom if you can

**Comment by dave-code-ruiz** [comment]
Send steps you follow and what not work

**Comment by n4tur3502** [comment]
Ok, after a bit of fiddling with restarting the led strip and stuff i got it to connect and works fine.

**Comment by dave-code-ruiz** [comment]
Great news,  im happy for you
