### ISSUE TITLE
Error tryng to add lights

### ISSUE THREAD

**Issue by Giangione76** [dave-code-ruiz/elkbledom#58]
I've installed this integration from HACS but anytime I try to add from integration panel an error message (in italian) says me : "impossible to load configuration flow: {"message":"Invalid handler specified"}" with only an ok button that end the configuration process. What can I do?

**Comment by dave-code-ruiz** [comment]
Send me you log, you can see how to in read.me

**Comment by Giangione76** [comment]
2024-01-14 23:38:26.092 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration elkbledom: No module named 'bluetooth_sensor_state_data'

I

**Comment by dave-code-ruiz** [comment]
Hi, 

I think you are using old version of integration elkbledom, now i no use this module "bluetooth_sensor_state_data" you can verify it in elkbledom.py line 17 module was commented

#throw error, see issue #43
#from bluetooth_sensor_state_data import BluetoothData

Anyway you can see more info in #43

**Comment by dave-code-ruiz** [comment]
sorry, i see now i have not new release for solves it, i will create it soon , download it for solves your issue
