### ISSUE TITLE
LED strip not returning any data

### ISSUE THREAD

**Issue by grintroy** [dave-code-ruiz/elkbledom#59]
My [cheap LED strip from AliExpress](https://www.aliexpress.com/item/1005005174831591.html) is recognized automatically, but it throws an error when trying to configure it.

```
This error originated from a custom integration.

Logger: custom_components.elkbledom.elkbledom
Source: custom_components/elkbledom/elkbledom.py:547
Integration: elkbledom (documentation, issues)
First occurred: 11:17:10 PM (6 occurrences)
Last logged: 11:19:08 PM

ELK-BLEDOB: Device unexpectedly disconnected; RSSI: -68
```

```
This error originated from a custom integration.

Logger: custom_components.elkbledom.elkbledom
Source: custom_components/elkbledom/elkbledom.py:435
Integration: elkbledom (documentation, issues)
First occurred: 11:17:47 PM (1 occurrences)
Last logged: 11:17:47 PM

Error getting status: ELK-BLEDOB - BE:60:B0:00:88:21: Failed to connect after 4 attempt(s): failed to discover services, device disconnected
```

I can connect to it through `gatttool`. However, both `primary` and `Characteristics` commands return nothing:

```
$ gatttool -I
[                 ][LE]> connect be:60:b0:00:88:21
Attempting to connect to be:60:b0:00:88:21
Connection successful
[be:60:b0:00:88:21][LE]> primary
Error: Discover all primary services failed: Request attribute has encountered an unlikely error
```

**Comment by dave-code-ruiz** [comment]
Your led strip it is not supported, 

https://github.com/dave-code-ruiz/elkbledom?tab=readme-ov-file#supported-strips

All my integration use attr handle with uuid: 00001800-0000-1000-8000-00805f9b34fb and you cannot access to it

[be:59:7a:00:08:xx][LE]> primary
attr handle: 0x0001, end grp handle: 0x0003 uuid: 00001800-0000-1000-8000-00805f9b34fb

It is no possible to use it if you can not write anything to it.

Sometimes you have to send a special command to unlock it, but in your case I don't know, search on Google in case you find something about this.

For the integration to work, the "primary" command must return at least that attribute

attr handle: 0x0001, end grp handle: 0x0003 uuid: 00001800-0000-1000-8000-00805f9b34fb

**Comment by grintroy** [comment]
@dave-code-ruiz I understand. This is odd however, because I can use the Lotus Lantern app no problem.

Also, I managed to set this LED strip up while I was using Homebridge a while ago using [this](https://github.com/Lyliya/homebridge-ledstrip-ble), although it was not reliable.

**Comment by dave-code-ruiz** [comment]
ok, it is possible you have another problem, If other element connect to the strip, the strip is blocked from connecting and HA cannot connect again to it
you can stop integration with homebridge and try again primary command, if it works you can try integration again

post me results
