### ISSUE TITLE
Live state polling dont work.

### ISSUE THREAD

**Issue by nagoz** [dave-code-ruiz/elkbledom#61]
Hello,

I want to change color on my Led strip when my screen colors change. So I write a python script to get average color and send color to my Led strip through HA.
The color change in state but the LED Strip don't change.
I saw that this is  a known issue.

Do you know when the issue will be resolved ?

Thank you

**Comment by dave-code-ruiz** [comment]
i need more information or example code to do something, i think change this color is done in HA code not in my integration code, if my code has to do it, i dont know how to do it, i need to investigate another light integration that do it

**Comment by nagoz** [comment]
thanks
