### ISSUE TITLE
More than 1 light

### ISSUE THREAD

**Issue by Majikmonke** [dave-code-ruiz/elkbledom#63]
Hi

Is it possible to have more than 1 light on HA? I have one all set up and working fine and it keeps popping up that it finds the second but fails to connect.

**Comment by dave-code-ruiz** [comment]
I have two strips working together and know some user have 10 at the same time

**Comment by Majikmonke** [comment]
I just can't add the second it just states that it failed to connect but every few hours it finds it via bluetooth

**Comment by dave-code-ruiz** [comment]
i think you haven´t problems with strips working together, you can test it going to HA, deleting first strip and testing add only second strip.

To try to help you with problems with your second strip i need you enable debug mode, test to connect strip with HA and send me log, you can enable debug mode with:

https://github.com/dave-code-ruiz/elkbledom?tab=readme-ov-file#enable-debug-mode

**Comment by Majikmonke** [comment]
working one deleted and debugging enabled, where do i get the log from?

**Comment by Majikmonke** [comment]
Hi

I believe that this is the code

This error originated from a custom integration.

Logger: custom_components.elkbledom.elkbledom
Source: custom_components/elkbledom/elkbledom.py:547
integration: ElkBLEDOM (documentation, issues)
First occurred: 13:19:43 (1 occurrences)
Last logged: 13:19:43

ELK-BLEDOM0E: Device unexpectedly disconnected; RSSI: -90


Regards


Dan Scate

________________________________

**Comment by Majikmonke** [comment]
This error originated from a custom integration.

Logger: custom_components.elkbledom.elkbledom
Source: custom_components/elkbledom/elkbledom.py:435
integration: ElkBLEDOM (documentation, issues)
First occurred: 08:42:07 (9 occurrences)
Last logged: 09:01:02

Error getting status: ELK-BLEDOM - BE:59:4D:00:11:34: Failed to connect after 9 attempt(s): No backend with an available connection slot that can reach address BE:59:4D:00:11:34 was found: The proxy/adapter is out of connection slots or the device is no longer reachable; Add additional proxies (https://esphome.github.io/bluetooth-proxies/) near this device
Error getting status: ELK-BLEDOM - BE:59:4D:00:11:34: Failed to connect after 10 attempt(s): No backend with an available connection slot that can reach address BE:59:4D:00:11:34 was found: The proxy/adapter is out of connection slots or the device is no longer reachable; Add additional proxies (https://esphome.github.io/bluetooth-proxies/) near this device

**Comment by dave-code-ruiz** [comment]
yes, this errors codes are related with fails to connect to strip.

The reason can be:

- the device is no longer reachable - strip and raspberry distance are so long
- No backend with an available connection slot - strip are connected to another bluetooth
- Device unexpectedly disconnected - this error can be shown sometimes, but if it be shown when you can try to connect it is posible you have two strip with same MAC but it is extrange , one of your strip's mac is  BE:59:4D:00:11:34 you can see it in logs.

good luck with the solution

**Comment by Majikmonke** [comment]
Hi

The HA is about 2 metres away from the light device and I have deleted all other apps etc so shouldn't be connected elsewhere.

HA find the device multiple times a day but just will not connect. I will just use the remote for that light going forward.


Regards


Dan Scate

________________________________

**Comment by dave-code-ruiz** [comment]
I'm sorry I can't help you i think your error is related with bluetooth and library "bleak" i use to connect, not with my integration code
if you need something more you can open new issue
