### ISSUE TITLE
Connecting but still getting an error.

### ISSUE THREAD

**Issue by m6els** [dave-code-ruiz/elkbledom#64]
Hey there, when connecting my ELK-BLEDOM light strip it spits out an error here. Home Assistant even automatically recognises the light strip but just wont connect. Any thoughts?

![image](https://github.com/dave-code-ruiz/elkbledom/assets/100724188/15d058a2-d5b2-4b84-9aa8-ce17a9dcc3ed)

Heres what my logs are saying

![Screenshot 2024-04-04 at 03 35 41](https://github.com/dave-code-ruiz/elkbledom/assets/100724188/2778ba94-bf9b-47bd-b704-be2303249094)

**Comment by dave-code-ruiz** [comment]
You need to locate the error in the log, it is not possible that this log corresponds to this error.
On the other hand, when an LED strip is discovered it is because it can be linked, this is why the log that you indicate appears, try placing the strip near the bluetooth
