### ISSUE TITLE
New device

### ISSUE THREAD

**Issue by shaeser** [dave-code-ruiz/elkbledom#65]
Dear,

I have an ELK-BLEDOM device (pool light rgb) from amazon  /  https://www.amazon.nl/-/en/dp/B0BX53X749?ref=ppx_yo2ov_dt_b_product_details&th=1

 with uuid: 0000FFF0-0000-1000-8000-00805F9B3fBB as an primary service
Custom characteristic: uuid: 0000FFF4 (notify) and 0000FFF3

I hope this will work within Home Assistant.

thanks in advance

Stefan

**Comment by dave-code-ruiz** [comment]
I hope too, post new issue if you have problems with it
