### ISSUE TITLE
Nrw device wont work

### ISSUE THREAD

**Issue by shaeser** [dave-code-ruiz/elkbledom#66]
Dear,

I have an ELK-BLEDOM device (pool light rgb) from amazon / https://www.amazon.nl/-/en/dp/B0BX53X749?ref=ppx_yo2ov_dt_b_product_details&th=1

with uuid: 0000FFF0-0000-1000-8000-00805F9B3fBB as an primary service
Custom characteristic: uuid: 0000FFF4 (notify) and 0000FFF3

Its not recognized, and if i add it manual also not.

**Comment by shaeser** [comment]
![Screenshot_20240412-081829](https://github.com/dave-code-ruiz/elkbledom/assets/137930143/87d0246b-2622-4086-89f4-1631e6eb16ad)

At 1meter distance from the coördinator

**Comment by dave-code-ruiz** [comment]
I need debug log to know more about.

You can see readme.md to know how to enable debug mode

**Comment by dave-code-ruiz** [comment]
https://github.com/dave-code-ruiz/elkbledom?tab=readme-ov-file#enable-debug-mode

**Comment by shaeser** [comment]
I've put the code in configuration.yaml but wont get an log message.

Op za 20 apr 2024 11:14 schreef Dave Code ***@***.***>:

**Comment by shaeser** [comment]
![Screenshot_20240421-191626](https://github.com/dave-code-ruiz/elkbledom/assets/137930143/1a2f4043-19d3-4c5b-b5bb-cab9588f4d0a)

**Comment by dave-code-ruiz** [comment]
> I've put the code in configuration.yaml but wont get an log message.

Sorry, Without log information is not possible to help you

**Comment by shaeser** [comment]
![Screenshot_20240421-192023](https://github.com/dave-code-ruiz/elkbledom/assets/137930143/c950eb83-e9e5-4586-8be7-2245f73a5f1b)


Is this ok?

**Comment by dave-code-ruiz** [comment]
2024-04-23 20:36:32.078 ERROR (MainThread) [custom_components.elkbledom.elkbledom] Error getting status: ELK-BLEDOM       - BE:59:EF:01:2D:61: Failed to connect after 9 attempt(s): No backend with an available connection slot that can reach address BE:59:EF:01:2D:61 was found: The proxy/adapter is out of connection slots or the device is no longer reachable; Add additional proxies 

Our led strip have only one slot connection , if another device is connected you will receive this Error,  disconnect all device connected

**Comment by dave-code-ruiz** [comment]
Push DISCONNECT and restart HA

**Comment by Soundgeek7** [comment]
Where do I push disconnect? What do I disconnect?

**Comment by dave-code-ruiz** [comment]
you say you have same issue, if you use mobile app to connect to strip, you need to disconnect it , 

Only one device can be connected over bluetooth

![image](https://github.com/dave-code-ruiz/elkbledom/assets/34915602/302f2d74-c9a2-49c2-a64f-4b504c4ec389)

**Comment by Soundgeek7** [comment]
I had gone around and turn off Bluetooth on all my devices and still getting the same error.

**Comment by rgnyldz** [comment]
I too have the same issue. It was working in the past but now I always get "Unable to connect to Elkbledom" error. Below is my log;

```
This error originated from a custom integration.

Logger: custom_components.elkbledom.elkbledom
Source: custom_components/elkbledom/elkbledom.py:435
integration: elkbledom (documentation, issues)
First occurred: 21:08:28 (3 occurrences)
Last logged: 21:27:27

Error getting status: ELK-BLEDOB - BE:60:4C:00:1C:50: Failed to connect after 4 attempt(s): TimeoutError
```

**Comment by dave-code-ruiz** [comment]
If you use mobile app to connect to strip, you need to disconnect it 

Only one device can be connected over bluetooth

My integration detect most of suppotted les, it is possible it is not supported
