### ISSUE TITLE
Can't connect using gatttool

### ISSUE THREAD

**Issue by dinde** [dave-code-ruiz/elkbledom#69]
Hello,

Debian 12.5 (non-free, volatile)
dbus-broker installed
docker home assistant with dbus mounted according home assistant bluetooth page.

Attempting to connect to BE:59:60:01:XX:YY
Error: connect to BE:59:60:01:XX:YY: Operation not supported (95)

When I try to add the integration:
Echec de la connexion ? Elkbledom

I use the built-in bluetooth card which is a broadcom and firmware are installed.

I can scan using bluetoothctl but strip doesn't show up.

Not sure what I'm doing wrong here.
Thanks for inputs :)

**Comment by dave-code-ruiz** [comment]
This is a connection error:

Error: connect to BE:59:60:01:XX:YY: Operation not supported (95)

Sorry i cant help you with this.
