### ISSUE TITLE
Brightness and color selecting not working 

### ISSUE THREAD

**Issue by Nubstex** [dave-code-ruiz/elkbledom#7]
![image](https://user-images.githubusercontent.com/91033840/186464496-4b24efc9-1e6d-4ab4-9b8a-0e4bc4082c36.png) //it shows when i try to select color
(Polish language)
I can't select color from wheel and can't adjust brightness.  
Also can't find where i can switch back to solid mode.

**Comment by dave-code-ruiz** [comment]
please try with new version and post results
